### ISSUE TITLE
Can't save configuration changes

### ISSUE THREAD

**Issue by garthk** [auth0-extensions/auth0-logs-to-papertrail#11]
After installing the extension, attempts to change `SLACK_SEND_SUCCESS` and `LOG_LEVEL` fail. After hitting Save:

* Most input fields become blank
* There's a delay
* The console gets an error: `PUT https://sandbox8-au.it.auth0.com/api/cron/TENANTNAME/NONCE 400 (Bad Request)`
* The body of the 400 response contains JSON with `message`: Invalid payload: ValidationError: child "schedule" fails because ["schedule" invalid cron string]
* This occurs whether trying to change the schedule or not

**Comment by garthk** [comment]
We haven't had to change the settings since setting the extension up, but have no reason to believe the problem fixed itself.

**Comment by fyockm** [comment]
@garthk I believe this was a problem with the Extension Gallery, and not the extension itself. I just tested and it does appear to be fixed. Closing this issue. Please reopen if you find otherwise.
